name: ci

on:
  pull_request_target:
    # when using teardown: 'true', add default event types + closed event type
    types: [opened, synchronize, reopened, closed]
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and export
        run: |
          make images

      - name: Export Docker Target Image
        run: |
          GIT_VERSION=$(git describe --tags --always)
          docker save gocrane/craned:${GIT_VERSION} -o "gocrane-craned-${GIT_VERSION}.tar"
          docker save gocrane/metric-adapter:${GIT_VERSION} -o "gocrane-metric-adapter-${GIT_VERSION}.tar"
          docker save gocrane/crane-agent:${GIT_VERSION} -o "gocrane/crane-agent-${GIT_VERSION}.tar"
          docker save gocrane/dashboard:${GIT_VERSION} -o "gocrane/dashboard-${GIT_VERSION}.tar"

      - id: git-versions
        run: |
          echo "::set-output name=git-version::$(git describe --tags --always)"
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: gocrane-craned-${{steps.git-versions.outputs.git-version}}.tar
          path: gocrane-craned-${{steps.git-versions.outputs.git-version}}.tar
