name: build-images

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  packages: write
  
jobs:
  build-craned:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - id: git-versions
        run: |
          echo "::set-output name=git-version::$(git describe --tags --always)"
      - id: build-name-image
        run: |
          echo "::set-output name=build-name-image::gocrane/craned"
      - id: build-name-file
        run: |
          echo "::set-output name=build-name-file::$(echo "${{steps.build-name-image.outputs.build-name-image}}" | tr '/' '-')"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: docker-layer-caching-${{ github.workflow }}-${{steps.build-name-file.outputs.build-name-file}}-{hash}
          restore-keys: |
            docker-layer-caching-${{ github.workflow }}-${{steps.build-name-file.outputs.build-name-file}}-

      - name: Build and export
        run: |
          make image-craned

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: |
          IMAGE_NAME=${{steps.build-name-image.outputs.build-name-image}}
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=${{steps.git-versions.outputs.git-version}}
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME:$VERSION $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  build-metric-adapter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - id: git-versions
        run: |
          echo "::set-output name=git-version::$(git describe --tags --always)"
      - id: build-name-image
        run: |
          echo "::set-output name=build-name-image::gocrane/metric-adapter"
      - id: build-name-file
        run: |
          echo "::set-output name=build-name-file::$(echo "${{steps.build-name-image.outputs.build-name-image}}" | tr '/' '-')"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: docker-layer-caching-${{ github.workflow }}-${{steps.build-name-file.outputs.build-name-file}}-{hash}
          restore-keys: |
            docker-layer-caching-${{ github.workflow }}-${{steps.build-name-file.outputs.build-name-file}}-

      - name: Build and export
        run: |
          make image-metric-adapter

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: |
          IMAGE_NAME=${{steps.build-name-image.outputs.build-name-image}}
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=${{steps.git-versions.outputs.git-version}}
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME:$VERSION $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  build-crane-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - id: git-versions
        run: |
          echo "::set-output name=git-version::$(git describe --tags --always)"
      - id: build-name-image
        run: |
          echo "::set-output name=build-name-image::gocrane/crane-agent"
      - id: build-name-file
        run: |
          echo "::set-output name=build-name-file::$(echo "${{steps.build-name-image.outputs.build-name-image}}" | tr '/' '-')"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: docker-layer-caching-${{ github.workflow }}-${{steps.build-name-file.outputs.build-name-file}}-{hash}
          restore-keys: |
            docker-layer-caching-${{ github.workflow }}-${{steps.build-name-file.outputs.build-name-file}}-

      - name: Build and export
        run: |
          make image-crane-agent

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: |
          IMAGE_NAME=${{steps.build-name-image.outputs.build-name-image}}
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=${{steps.git-versions.outputs.git-version}}
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME:$VERSION $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  build-dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - id: git-versions
        run: |
          echo "::set-output name=git-version::$(git describe --tags --always)"
      - id: build-name-image
        run: |
          echo "::set-output name=build-name-image::gocrane/dashboard"
      - id: build-name-file
        run: |
          echo "::set-output name=build-name-file::$(echo "${{steps.build-name-image.outputs.build-name-image}}" | tr '/' '-')"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: docker-layer-caching-${{ github.workflow }}-${{steps.build-name-file.outputs.build-name-file}}-{hash}
          restore-keys: |
            docker-layer-caching-${{ github.workflow }}-${{steps.build-name-file.outputs.build-name-file}}-

      - name: Build and export
        run: |
          make image-dashboard

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: |
          IMAGE_NAME=${{steps.build-name-image.outputs.build-name-image}}
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=${{steps.git-versions.outputs.git-version}}
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME:$VERSION $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  post-comment:
    runs-on: ubuntu-latest
    needs:
      - build-craned
      - build-metric-adapter
      - build-crane-agent
      - build-dashboard
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - id: git-versions
        run: |
          echo "::set-output name=git-version::$(git describe --tags --always)"
      - name: maintain-comment
        uses: actions-cool/maintain-one-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            🎉 Successfully Build Images.
            | Image                                         | Pull Command                                              |
            | --------------------------------------------- | --------------------------------------------------------- |
            | ghcr.io/${{ github.repository_owner }}/gocrane/crane-agent:${{steps.git-versions.outputs.git-version}}    | docker pull ghcr.io/${{ github.repository_owner }}/gocrane/crane-agent:${{steps.git-versions.outputs.git-version}}    |
            | ghcr.io/${{ github.repository_owner }}/gocrane/dashboard:${{steps.git-versions.outputs.git-version}}      | docker pull ghcr.io/${{ github.repository_owner }}/gocrane/dashboard:${{steps.git-versions.outputs.git-version}}      |
            | ghcr.io/${{ github.repository_owner }}/gocrane/metric-adapter:${{steps.git-versions.outputs.git-version}} | docker pull ghcr.io/${{ github.repository_owner }}/gocrane/metric-adapter:${{steps.git-versions.outputs.git-version}} |
            | ghcr.io/${{ github.repository_owner }}/gocrane/craned:${{steps.git-versions.outputs.git-version}}         | docker pull ghcr.io/${{ github.repository_owner }}/gocrane/craned:${{steps.git-versions.outputs.git-version}}         |
            <!-- Created by actions-cool/maintain-one-comment -->
          body-include: '<!-- Created by actions-cool/maintain-one-comment -->'
