name: build-images

on: [pull_request]

jobs:
  build-craned:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and export
        run: |
          make image-craned

      - name: Export Docker Target Image
        run: |
          GIT_VERSION=$(git describe --tags --always)
          docker save gocrane/craned:${GIT_VERSION} -o "gocrane-craned-${GIT_VERSION}.tar"

      - id: git-versions
        run: |
          echo "::set-output name=git-version::$(git describe --tags --always)"
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: gocrane-craned-${{steps.git-versions.outputs.git-version}}.tar
          path: gocrane-craned-${{steps.git-versions.outputs.git-version}}.tar
          retention-days: 30

  build-metric-adapter:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and export
        run: |
          make image-metric-adapter

      - name: Export Docker Target Image
        run: |
          GIT_VERSION=$(git describe --tags --always)
          docker save gocrane/metric-adapter:${GIT_VERSION} -o "gocrane-metric-adapter-${GIT_VERSION}.tar"

      - id: git-versions
        run: |
          echo "::set-output name=git-version::$(git describe --tags --always)"
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: gocrane-metric-adapter-${{steps.git-versions.outputs.git-version}}.tar
          path: gocrane-metric-adapter-${{steps.git-versions.outputs.git-version}}.tar
          retention-days: 30

  build-crane-agent:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and export
        run: |
          make image-crane-agent

      - name: Export Docker Target Image
        run: |
          GIT_VERSION=$(git describe --tags --always)
          docker save gocrane/crane-agent:${GIT_VERSION} -o "gocrane-crane-agent-${GIT_VERSION}.tar"

      - id: git-versions
        run: |
          echo "::set-output name=git-version::$(git describe --tags --always)"
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: gocrane-crane-agent-${{steps.git-versions.outputs.git-version}}.tar
          path: gocrane-crane-agent-${{steps.git-versions.outputs.git-version}}.tar
          retention-days: 30

  build-dashboard:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and export
        run: |
          make image-dashboard

      - name: Export Docker Target Image
        run: |
          GIT_VERSION=$(git describe --tags --always)
          docker save gocrane/dashboard:${GIT_VERSION} -o "gocrane-dashboard-${GIT_VERSION}.tar"

      - id: git-versions
        run: |
          echo "::set-output name=git-version::$(git describe --tags --always)"
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: gocrane-dashboard-${{steps.git-versions.outputs.git-version}}.tar
          path: gocrane-dashboard-${{steps.git-versions.outputs.git-version}}.tar
          retention-days: 30
