name: 🔂 Crane PR Docs Preview

on:
  pull_request_target:
    # when using teardown: 'true', add default event types + closed event type
    types: [opened, synchronize, reopened, closed]

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - run: pip install mkdocs-material mkdocs-static-i18n mike
      
      - run: git log --oneline --decorate --max-count=10 && ls -la && cat docs/index.md && cat docs/index.zh.md

      - run: git log --oneline --decorate --max-count=10 && ls -la

      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: site
          teardown: 'true'
          build: |
           mkdocs build
